export {default as Visitka } from './Visitka'
export {default as Button } from './Button'
export {default as Navbar } from './Navbar'
export {default as TeamSlider } from './TeamSlider'
export {default as FaqQuestions } from './FaqQuestions'