export { default as Hero } from './Hero'
export { default as Stronger } from './Stronger'
// export { default as Services } from './Serveces'
export { default as About } from './About'
export { default as Team } from './Team'
export { default as Sender } from './Sender'
export { default as Proces } from './Process'
export { default as FreightServices } from './FreightServices'